src/main/java/com/eppo/sdk/EppoClient.java, src/main/java/com/eppo/sdk/exception/InvalidApiKeyException.java, src/main/java/com/eppo/sdk/helpers/ConfigurationStore.java, src/main/java/com/eppo/sdk/helpers/ExperimentConfigurationRequestor.java, src/main/java/com/eppo/sdk/helpers/FetchConfigurationsTask.java
Fixes a couple bugs with the configuration requestor:
- It treated request timeouts as fatal errors - these should not stop the polling process
- It did not give a meaningful error for the unauthorized case, just said "Request not allowed"
- There was no logging of non-fatal errors - I added [SLF4j logger](https://www.slf4j.org/). SLF4j is a facade that allows consumers of the SDK to choose their logging implementation ([reference](https://stackoverflow.com/a/69511735)).
Verified the following cases:
- Invalid API key throws error during initialization
- Simulated a request timeout by adding a delay to the RAC endpoint
- Tried other fatal exceptions such as an invalid base URL
=> Handle request timeouts and unauthorized errors

.gitignore, Makefile, pom.xml, src/main/java/com/eppo/sdk/EppoClient.java, src/main/java/com/eppo/sdk/constants/Constants.java, src/main/java/com/eppo/sdk/dto/Allocation.java, src/main/java/com/eppo/sdk/dto/ExperimentConfiguration.java, src/main/java/com/eppo/sdk/dto/ExperimentConfigurationResponse.java, src/main/java/com/eppo/sdk/dto/Rule.java, src/main/java/com/eppo/sdk/dto/Variation.java, src/main/java/com/eppo/sdk/helpers/ConfigurationStore.java, src/main/java/com/eppo/sdk/helpers/RuleValidator.java, src/test/java/com/eppo/sdk/EppoClientTest.java, src/test/java/com/eppo/sdk/deserializer/EppoValueDeserializerTest.java, src/test/java/com/eppo/sdk/helpers/RuleValidatorTest.java, src/test/java/com/eppo/sdk/helpers/ShardTest.java
---
labels: mergeable
---
[//]: #  (Link to the issue corresponding to this chunk of work)
Fixes Eppo-exp/eppo#4711
[//]: #  (Why is this change required? What problem does it solve?)
Design Doc: https://www.notion.so/eppo/Feature-Flagging-API-Design-d768a09de1194cebb04ef8af157fda57
[//]: # (Describe your changes in detail)
Updated the `getAssignment` logic to use the **allocation** (variations + exposure) for the matched targeting rule. The API response inserts a default rule that always matches if the experiment does not have any rules.
See the above design doc for details
[//]: # (Please describe in detail how you tested your changes)
- Updated the e2e tests to use new test data for the V2 RAC response.
- Tested using the SDK from sample code
[//]: # (OPTIONAL)
[//]: # (Add one or …
=> Migrate Java SDK to use V2 Randomization Endpoint

.gitignore, Makefile
Made some change in the way we are pulling the test data. Earlier we were pulling the test data from gcp cloud storage. Now I am pulling the test data from a github repository.
=> Reading test data files from github repo instead of cloud storage

.github/workflows/publish-sdk.yml, Makefile
Currently, the publish Github workflow is now working because of 
- gpg key not added
Added the gpg private key and paraphase.
=> fixed pushing workflow

Makefile
I have seen a few times the `make test-data` action fail on github actions with what seems like the `git clone` command is running async:
```
0s
Run make test-data
rm -rf src/test/resources/
mkdir -p src/test/resources//temp
cd src/test/resources//temp \
&& git clone -b main --depth [1](https://github.com/Eppo-exp/java-server-sdk/actions/runs/6041608861/job/16425318053#step:5:1) --single-branch https://github.com/Eppo-exp/sdk-test-data.git \
&& rm -rf RepoName/.git/
cp src/test/resources//temp/sdk-test-data/rac-experiments-v3.json src/test/resources/
cp -r src/test/resources//temp/sdk-test-data/assignment-v2 src/test/resources/
rm -rf src/test/resources//temp
Cloning into 'sdk-test-data'...
cp: cannot stat 'src/test/resources//temp/sdk-test-data/rac-experiments-v3.json': No such file or …
```
=> fix makefile test-data on github actions

pom.xml
In the current build we were getting below error
```
gpg: signing failed: Inappropriate ioctl for device
```
Added the configuration mentioned in the [doc](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#extra-setup-for-pomxml) to avoid above error
=> fixed GPG settings

src/main/java/com/eppo/sdk/EppoClient.java, src/main/java/com/eppo/sdk/dto/AssignmentLogData.java, src/main/java/com/eppo/sdk/helpers/ExperimentHelper.java
Made below changes in the code.
- Added helper class `ExperimentHelper` to generate experiment key
- Modified the `AssignmentLogData` dto class, added two new field `featureFlag` and `allocation`.
- Initialise `featureFlag` and `allocation` with feature flag key and allocation key respectively while calling assignment log callback.
=> Added allocation key in the assignment logging event data

pom.xml, src/main/java/com/eppo/sdk/EppoClient.java, src/test/java/com/eppo/sdk/EppoClientTest.java
note to reviewers: the diff of `EppoClientTest.java` is a little strange reviewing side by side please take care.
unit tests access json via the parsed method in order to exercise both the `JsonNode` and `String` return types.
=> add support for getParsedJSONAssignment method returning JsonNode (FF-896)

src/main/java/com/eppo/sdk/EppoClient.java, src/main/java/com/eppo/sdk/dto/EppoClientConfig.java, src/main/java/com/eppo/sdk/helpers/ConfigurationStore.java, src/main/java/com/eppo/sdk/helpers/ExperimentConfigurationRequestor.java, src/test/java/com/eppo/sdk/EppoClientTest.java
The default SDK behavior will be to NOT throw exceptions from any of the public methods; just log to `stderr`.
When building a client configuration customers can choose to disable graceful mode, such as for development and testing.
In our javascript commons we added `try/catch` to all top level functions - should we keep that behavior here too for consistency? https://github.com/Eppo-exp/js-client-sdk-common/pull/16
=> add graceful mode by default that does not throw exceptions (FF-949)

.github/workflows/lint-test-sdk.yml, .github/workflows/publish-sdk.yml, Makefile, pom.xml, src/main/java/com/eppo/sdk/EppoClient.java, src/main/java/com/eppo/sdk/dto/EppoValue.java, src/main/java/com/eppo/sdk/helpers/ConfigurationStore.java, src/main/java/com/eppo/sdk/helpers/EppoHttpClient.java, src/main/java/com/eppo/sdk/helpers/ExperimentConfigurationRequestor.java, src/main/java/com/eppo/sdk/helpers/InputValidator.java, src/test/java/com/eppo/sdk/helpers/RuleValidatorTest.java
Eppo's customers need support for Java 8.
There are certain language support not available in java 8 and libraries that are not available. For compatibility:
* `List.of` replaced with `Arrays.asList`
* `java.net.http` replaced with `org.apache.http`
* `isBlank` replaced with `isPresent`
**support for local development**
It is not possible to install java 8 on apple m-processor machines.
```
brew install openjdk@8
openjdk@8: The x86_64 architecture is required for this software.
Error: openjdk@8: An unsatisfied requirement failed this build.
```
Created a docker-based compilation to enable developers to more easily contribute:
```
make docker-compile-java
...
[WARNING] /usr/src/myapp/src/main/java/com/eppo/sdk/EppoClient.java: Recompile with -Xlint:unchecked for details.
[INFO] …
```
=> add compatibility for java 8

src/main/java/com/eppo/sdk/helpers/FetchConfigurationsTask.java
* Have `FetchConfigurationsTask` catch runtime exceptions and log the error
* Without this change, arbitrary exceptions would prevent tasks from being rescheduled. When this happens the SDK is still _technically_ functional via it's in-memory cache used by the `ConfigurationStore`... but all further communication between the SDK and Eppo Cloud is effectively terminated.
* Fixed an issue calculating jitter
* `(long) Math.random()` is always cast to `0`.
=> FetchConfigurationsTask is more fault tolerant

.github/workflows/publish-sdk.yml, pom.xml
Our publish action is hitting a timeout. As a hail mary, I'm updating the latest version of the plugin.
```
Uploaded to ossrh: [https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/cloudeppo-1026/cloud/eppo/eppo-server-sdk/2.4.1/eppo-server-sdk-2.4.1.jar](https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/cloudeppo-1026/cloud/eppo/eppo-server-sdk/2.4.1/eppo-server-sdk-2.4.1.jar) (83 kB at 187 kB/s)
Uploading to ossrh: [https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/cloudeppo-1026/cloud/eppo/eppo-server-sdk/2.4.1/eppo-server-sdk-2.4.1.pom](https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/cloudeppo-1026/cloud/eppo/eppo-server-sdk/2.4.1/eppo-server-sdk-2.4.1.pom)
Progress (1): 4.1/8.3 kB
Progress …
```
=> Latest version of staging plugin and increased timeout

pom.xml, src/main/java/com/eppo/sdk/EppoClient.java, src/main/java/com/eppo/sdk/constants/Constants.java, src/test/java/com/eppo/sdk/EppoClientTest.java
_Eppo Internal:_ 🎟️ **Ticket:** [FF-1971 - Have bandit use flag-config endpoint](https://linear.app/eppo/issue/FF-1971/have-bandit-use-flag-config-endpoint)
This PR introduces two quality-of-life changes:
1. Update the endpoint the SDK loads bandits from to match where it will soon load the Universal Flag Configuration (UFC)
2. Create dedicated `getBanditAction()` functions to get bandit actions (separating from `getStringAssignment()`)
=> Update endpoint; separate bandit functions

src/main/java/com/eppo/sdk/dto/EppoValue.java, src/main/java/com/eppo/sdk/helpers/RuleValidator.java, src/test/java/com/eppo/sdk/helpers/RuleValidatorTest.java
Fixes `oneOf` and `notOneOf` evaluation for Number and Boolean types.
The targeting rule documentation states that [oneOf is evaluated](https://docs.geteppo.com/feature-flagging/targeting#supported-rule-operators) by casting booleans and numbers to a string.
However, [there was a recent update to the SDK that changed the implementation of stringValue()](https://github.com/Eppo-exp/java-server-sdk/blob/main/src/main/java/com/eppo/sdk/dto/EppoValue.java#L76); The method now returns `null` when the `EppoValue` is either a number or boolean type.
The proposed change does the following:
* Casts fields using `toString()` instead of `stringValue()` when evaluating `oneOf` or `notOneOf`
* Changes the string representation of a number to better reflect the numbers intended type
* Since `double` is …
=> [NO TASK] Fix oneOf comparisons for both Booleans and Numbers (#14)

pom.xml, src/main/java/com/eppo/sdk/deserializer/BanditsDeserializer.java, src/test/resources/bandits/bandits-parameters-1.json
_Eppo Iternal:_
🎟️ **Ticket:** [FF-2218 - JS SDK - local and chrome storage caches should be isolated per-API key](https://linear.app/eppo/issue/FF-2230/js-sdk-local-and-chrome-storage-caches-should-be-isolated-per-api-key)
The Eppo servers are changing the way categorical attribute coefficients are transmitted to be an object (mapping) instead of an array (list of keys and values). This PR updates the test data to reflect that and the parameter deserializer to handle it.
=> Ingest categorical coefficients as an object (Map)

pom.xml, src/main/java/com/eppo/sdk/deserializer/BanditsDeserializer.java, src/test/resources/bandits/bandits-parameters-1.json
_Eppo Internal:_ 🎟️ **Ticket:** [FF-2269](https://linear.app/eppo/issue/FF-2269/adjust-java-sdk-and-upgrade-dogfood-bandit-to-handle-coefficients-as)
This change has the SDK ingest bandit parameter coefficients as a map of actions to that action's coefficients rather than as a list of an action key and associated coefficients.
=> Handle bandit parameter coefficients provided as maps (Objects)

build.gradle, src/main/java/com/eppo/sdk/EppoClient.java, src/test/java/com/eppo/sdk/EppoClientTest.java
_Eppo Internal_:
🎟️  **Ticket:** [FF-3067 - Java SDK should pass through Common SDK API when packaging](https://linear.app/eppo/issue/FF-3067/java-sdk-should-pass-through-common-sdk-api-when-packaging)
Upstream use of this SDK needs access to interfaces in the Common SDK (e.g., `Attributes`) so we configure out build to pass them through.
We also configure out build to target Java 8 so the package is compatible with it.
Lastly, added some basic documentation to public methods.
=> Pass through Common SDK API

.github/workflows/lint-test-sdk.yml
🎟️ Fixes FF-3090 towards FF-3085
👯‍♂️ **Related PRs**
- [sdk-test-data#58](https://github.com/Eppo-exp/sdk-test-data/pull/58)
- [js-client-sdk#96](https://github.com/Eppo-exp/js-client-sdk/pull/96)
- [python-sdk#65](https://github.com/Eppo-exp/python-sdk/pull/65)
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). There are a number of limitations to this setup:
- Test …
=> quality: Parameterize branch names for test workflow

.github/workflows/lint-test-sdk.yml
Adding Java version 21 to the testing matrix to ensure the SDK operates as expected in a newer version of Java
=> Include Java version 21 in tests

build.gradle, src/main/java/com/eppo/sdk/EppoClient.java, src/test/java/com/eppo/sdk/EppoClientTest.java
Picks up latest from common package.
=> chore: bump common API version to 3.3.1

build.gradle, src/main/java/com/eppo/sdk/EppoClient.java, src/test/java/com/eppo/sdk/EppoClientTest.java
Available by upgrading to the latest version of the common SDK
=> feat: assignment and bandit caching

Makefile, README.md, build.gradle, src/main/java/cloud/eppo/EppoClient.java, src/main/java/cloud/eppo/FetchConfigurationsTask.java, src/test/java/cloud/eppo/EppoClientTest.java
- Update to latest `sdk-common-jvm`
- Tests for ensuring EppoClient still gives assignment if it fails init.
=> fix: Respect graceful mode on init (from sdk-common-jvm)

README.md, build.gradle, src/main/java/cloud/eppo/EppoClient.java, src/test/java/cloud/eppo/EppoClientTest.java
towards FF-3558
🎟️ [FF-3558](https://linear.app/eppo/issue/FF-3558/unify-sdk-request-baseurl)
Most, nearly all in fact, of the SDKs use a baseUrl of https://fscdn.eppo.cloud/api and endpoint constants of `/flag-config/v1/config` and `/flag-config/v1/bandits` for flag and bandit requests.
iOS and, at some point, the Java SDK [stopped following](https://github.com/Eppo-exp/sdk-common-jdk/blob/main/src/main/java/cloud/eppo/ConfigurationRequestor.java#L12) this [convention](https://github.com/Eppo-exp/sdk-common-jdk/blob/main/src/main/java/cloud/eppo/Constants.java) instead putting the /apiportion in the endpoint string.
All of the SDKs need to follow the common convention in order for our cross-SDK testing tools (scenario testing, benchmarking) to work seamlessly.
- major version bump …
=> chore: latest common package and move `/api` to baseUrl

build.gradle, src/main/java/cloud/eppo/EppoClient.java, src/test/java/cloud/eppo/EppoClientTest.java
_Eppo Internal_
🎟️ Fixes FF-3454
📜 [DD](https://www.notion.so/eppo/New-Java-SDK-methods-getConfiguration-and-getFlagType-19a49cc0114380709ff3e69f020650d8)
- updates to sdk-common-jdk:3.8.0
- `getConfiguration`
- `startPolling` and `stopPolling` as instance methods on `EppoClient`
- bump to v5.0.0
**Breaking Change** 
The static method `EppoClient.stopPolling()` has been removed in favour of using the instance method `stopPolling()`.
```java
// This method has been removed
EppoClient.stopPolling();
// use this instead
getInstance().stopPolling();
// If you are unsure whether the EppoClient has been initialized when you wish to call stopPolling, try-catch:
try {
EppoClient.getInstance().stopPolling();
} catch (IllegalStateException ex) {
// pass: Indicates that the singleton Eppo Client has …
```
=> feat: update to latest common for new methods, major bump

README.md, build.gradle, src/main/java/cloud/eppo/EppoClient.java, src/test/java/cloud/eppo/EppoClientTest.java
---
labels: mergeable
---
_Eppo Internal_
[//]: #  (Link to the issue or doc corresponding to this chunk of work)
🎟️ Fixes ff-4116
📜 [Design Doc](https://www.notion.so/eppo/onConfigurationChanged-method-1af49cc0114380c6bd97f4ea1f780608) 
Pick up latest changes from common
- minor feat: `onConfigurationChange`
[ff-4117](https://linear.app/eppo/issue/FF-4117/[docs]-update-docs-with-config-change-callback-method)
=> feat: onConfigurationChange
